name: Stack CI

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Haskell
        uses: haskell-actions/setup@v2
        with:
          enable-stack: true

      - name: Cache Stack dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Stack build
        run: stack --no-terminal build

      - name: Stack test
        run: stack --no-terminal test
